FROM ruby:2.7.3
RUN apt-get update -qq && apt-get install -y nodejs postgresql-client

RUN mkdir /aim

WORKDIR /aim

COPY Gemfile /aim/Gemfile
COPY Gemfile.lock /aim/Gemfile.lock

RUN bundle install

COPY . /aim

EXPOSE 3000

CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]