version: '3'
volumes:
  postgres_data: {}
services:
  app:
    image: dockermy7777/aim:mini-app_v1
    environment:
      RAILS_ENV: production-aim-mini
      RACK_ENV: production
      SECRET_KEY_BASE: <%= Rails.application.credentials.dig(:aim_mini, :secret_key_base) %>
    depends_on:
      - db
    networks:
      - aim-mini-network
    #command: bundle exec rails db:migrate
    #command: bundle exec puma -C config/puma.rb
  db:
    image: dockermy7777/aim:mini-db_v1
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: <%= Rails.application.credentials.dig(:aim_mini, :db) %>
      POSTGRES_USER: <%= Rails.application.credentials.dig(:aim_mini, :db_user_name) %>
      POSTGRES_PASSWORD: <%= Rails.application.credentials.dig(:aim_mini, :db_password) %>
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aim-mini-network
  web:
    image: dockermy7777/aim:mini-web_v1
    depends_on:
      - app
    ports:
      - 80:80
    networks:
      - aim-mini-network
networks:
  aim-mini-network:
    external: true