databases:
  - name: aim_db
    databaseName: aim_db
    user: wondman_
    region: singapore

services:
  - type: web
    name: Aim_Rails
    env: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['RENDER_COM_DATABASE_URL'] %>
        fromDatabase:
          name: aim_db
          property: connectionString
      - key: <%= ENV['RENDER_COM_RAILS_MASTER_KEY'] %>
        sync: false