version: 2.1

# このプロジェクトで実行するジョブの定義
jobs:
  build:
    docker:
      - image: dockermy7777/aim:mini-app-latest
        auth:
          username: dockermy7777
          password: $DOCKERHUB_PASSWORD
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
          POSTGRES_DB: $POSTGRES_DB
    environment:
      BUNDLE_JOBS: "4"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: postgres
      PGPASSWORD: $POSTGRES_PASSWORD
      RAILS_ENV: test
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rails db:create
      - run: bundle exec rails db:migrate
      - run: bundle exec rails db:schema:load --trace
      - run: bundle exec rspec


  deploy_to_render:
     docker:
      - image: dockermy7777/aim:mini-app-latest
        auth:
          username: dockermy7777
          password: $DOCKERHUB_PASSWORD  # コンテキスト/プロジェクト UI 環境変数の参照
     steps:
      - checkout
      - run:
          name: Deploy to Render.com
          command: |
            curl -X POST "https://api.render.com/deploy/srv-$RENDER_PROJECT_ID?key=$DEPLOY_KEY" 
  deploy_to_EC2_mini:
    docker:
      - image: dockermy7777/aim:mini-app-latest
        auth:
          username: dockermy7777
          password: $DOCKERHUB_PASSWORD  # コンテキスト/プロジェクト UI 環境変数の参照
      - image: circleci/ruby:2.7.3
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "fc:15:79:51:be:36:08:e0:44:9f:a3:1d:4e:15:c0:e2"
      #- run: curl ipecho.net/plain; echo
      #- run: bundle install
      #- run: docker ps
      #- run: docker build -t my_image .
      #- run: bundle exec cap production-aim-mini my_custom_task:test_local
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
#      - run: |
#          TAG=0.1.$CIRCLE_BUILD_NUM
#          docker build -t CircleCI-Public/circleci-demo-docker:$TAG .
#          echo $DOCKER_PASS | docker login -u dockermy7777 --password-stdin
#          docker push CircleCI-Public/circleci-demo-docker:$TAG
      - run: bundle exec cap production-aim-mini my_custom_task:local_ImageBuild
      - run: bundle exec cap production-aim-mini my_custom_task:test_ec2
#      - deploy:
#          name: Capistrano deploy
          #command: bundle exec cap production-aim-mini deploy
#          command: bundle exec cap production-aim-mini my_custom_task:test_local
#          command: bundle exec cap production-aim-mini my_custom_task:test_ec2
# ジョブの実行順の指定
workflows:
  build_and_test:
    jobs:
      - build
      - deploy_to_render:
          context: render
      - deploy_to_EC2_mini:
          filters:
            branches:
              only: main