version: 2.1

# このプロジェクトで実行するジョブの定義
jobs:
  build:
    docker:
      - image: dockermy7777/aim:mini-app-latest
        auth:
          username: dockermy7777
          password: $DOCKERHUB_PASSWORD
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: $POSTGRES_USER
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
          POSTGRES_DB: $POSTGRES_DB
    steps:
      - checkout
      - run: bundle install
      - run: rails db:create db:schema:load RAILS_ENV=test
      #- run: bundle exec rake db:migrate
      - run: bundle exec rspec spec/

  deploy_to_render:
     docker:
      - image: dockermy7777/aim:mini-app-latest
        auth:
          username: dockermy7777
          password: $DOCKERHUB_PASSWORD  # コンテキスト/プロジェクト UI 環境変数の参照
     steps:
      - checkout
      - run:
          name: Deploy to Render.com
          command: |
            curl -X POST "https://api.render.com/deploy/srv-$RENDER_PROJECT_ID?key=$DEPLOY_KEY" 
  deploy_to_EC2_mini:
    docker:
      - image: dockermy7777/aim:mini-app-latest
        auth:
          username: dockermy7777
          password: $DOCKERHUB_PASSWORD  # コンテキスト/プロジェクト UI 環境変数の参照
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "fc:15:79:51:be:36:08:e0:44:9f:a3:1d:4e:15:c0:e2"
      - deploy:
          name: Capistrano deploy
          command: bundle exec cap production-aim-mini deploy

# ジョブの実行順の指定
workflows:
  build_and_test:
    jobs:
      - build
      - deploy_to_render:
          context: render
#     - deploy_to_EC2_mini:
#         filters:
#           branches:
#             only: main